//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.10.09 at 02:37:29 AM PHT 
//


package reader_writer.message;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ChangeList complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ChangeList">
 *   &lt;complexContent>
 *     &lt;extension base="{}ParamType">
 *       &lt;sequence>
 *         &lt;element name="command" type="{}ChangeViewCommands"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ChangeList", propOrder = {
    "command"
})
public class ChangeList
    extends ParamType
{

    @XmlElement(required = true)
    protected ChangeViewCommands command;

    /**
     * Gets the value of the command property.
     * 
     * @return
     *     possible object is
     *     {@link ChangeViewCommands }
     *     
     */
    public ChangeViewCommands getCommand() {
        return command;
    }

    /**
     * Sets the value of the command property.
     * 
     * @param value
     *     allowed object is
     *     {@link ChangeViewCommands }
     *     
     */
    public void setCommand(ChangeViewCommands value) {
        this.command = value;
    }

}
