//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.10.04 at 10:56:33 PM PHT 
//


package reader_writer.message;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for MessageType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="MessageType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Ack"/>
 *     &lt;enumeration value="Confirm"/>
 *     &lt;enumeration value="Nack"/>
 *     &lt;enumeration value="NewList"/>
 *     &lt;enumeration value="ListChangeRequest"/>
 *     &lt;enumeration value="WriteRequest"/>
 *     &lt;enumeration value="WriteResponse"/>
 *     &lt;enumeration value="ReadRequest"/>
 *     &lt;enumeration value="ReadResponse"/>
 *     &lt;enumeration value="Release"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "MessageType")
@XmlEnum
public enum MessageType {

    @XmlEnumValue("Ack")
    ACK("Ack"),
    @XmlEnumValue("Confirm")
    CONFIRM("Confirm"),
    @XmlEnumValue("Nack")
    NACK("Nack"),
    @XmlEnumValue("NewList")
    NEW_LIST("NewList"),
    @XmlEnumValue("ListChangeRequest")
    LIST_CHANGE_REQUEST("ListChangeRequest"),
    @XmlEnumValue("WriteRequest")
    WRITE_REQUEST("WriteRequest"),
    @XmlEnumValue("WriteResponse")
    WRITE_RESPONSE("WriteResponse"),
    @XmlEnumValue("ReadRequest")
    READ_REQUEST("ReadRequest"),
    @XmlEnumValue("ReadResponse")
    READ_RESPONSE("ReadResponse"),
    @XmlEnumValue("Release")
    RELEASE("Release");
    private final String value;

    MessageType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static MessageType fromValue(String v) {
        for (MessageType c: MessageType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
