//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.10.04 at 10:56:33 PM PHT 
//


package reader_writer.message;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Nack complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Nack">
 *   &lt;complexContent>
 *     &lt;extension base="{}ParamType">
 *       &lt;sequence>
 *         &lt;element name="sender" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="missing_msgid" type="{}MessageIdentity"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Nack", propOrder = {
    "sender",
    "missingMsgid"
})
public class Nack
    extends ParamType
{

    @XmlElement(required = true)
    protected String sender;
    @XmlElement(name = "missing_msgid", required = true)
    protected MessageIdentity missingMsgid;

    /**
     * Gets the value of the sender property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSender() {
        return sender;
    }

    /**
     * Sets the value of the sender property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSender(String value) {
        this.sender = value;
    }

    /**
     * Gets the value of the missingMsgid property.
     * 
     * @return
     *     possible object is
     *     {@link MessageIdentity }
     *     
     */
    public MessageIdentity getMissingMsgid() {
        return missingMsgid;
    }

    /**
     * Sets the value of the missingMsgid property.
     * 
     * @param value
     *     allowed object is
     *     {@link MessageIdentity }
     *     
     */
    public void setMissingMsgid(MessageIdentity value) {
        this.missingMsgid = value;
    }

}
