//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.10.04 at 10:56:33 PM PHT 
//


package reader_writer.message;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for NewList complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="NewList">
 *   &lt;complexContent>
 *     &lt;extension base="{}ParamType">
 *       &lt;sequence>
 *         &lt;element name="new_viewid" type="{}ViewIdentity"/>
 *         &lt;element name="members" type="{}ProcessIdentity" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "NewList", propOrder = {
    "newViewid",
    "members"
})
public class NewList
    extends ParamType
{

    @XmlElement(name = "new_viewid", required = true)
    protected ViewIdentity newViewid;
    @XmlElement(required = true)
    protected List<ProcessIdentity> members;

    /**
     * Gets the value of the newViewid property.
     * 
     * @return
     *     possible object is
     *     {@link ViewIdentity }
     *     
     */
    public ViewIdentity getNewViewid() {
        return newViewid;
    }

    /**
     * Sets the value of the newViewid property.
     * 
     * @param value
     *     allowed object is
     *     {@link ViewIdentity }
     *     
     */
    public void setNewViewid(ViewIdentity value) {
        this.newViewid = value;
    }

    /**
     * Gets the value of the members property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the members property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMembers().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ProcessIdentity }
     * 
     * 
     */
    public List<ProcessIdentity> getMembers() {
        if (members == null) {
            members = new ArrayList<ProcessIdentity>();
        }
        return this.members;
    }

}
